# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master

environment:
  matrix:
    # AppVeyor installed Python versions
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON_INSTALL: "C:\\Python27"
    - PYTHON_INSTALL: "C:\\Python33"
    - PYTHON_INSTALL: "C:\\Python34"
    - PYTHON_INSTALL: "C:\\Python35"

install:
  # Make compiler available (use MSVC 2013, 32 bit)
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86

  # Check compiler version
  - cl

  # Prepend Python installation to PATH
  - set PATH=%PYTHON_INSTALL%;%PATH%

  # Check Python version
  - python --version

  # Install pytest
  - "%PYTHON_INSTALL%\\Scripts\\pip" install pytest

build_script:
  - python clcache.py --help
  - python clcache.py -s

test_script:
  # Run test files via py.test and generate JUnit XML. Then push test results
  # to appveyor.
  - ps: >-
      $wc = New-Object 'System.Net.WebClient'

      & $env:PYTHON_INSTALL\Scripts\py.test --junitxml .\unittests.xml unittests.py

      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))

      & $env:PYTHON_INSTALL\Scripts\py.test --junitxml .\integrationtests.xml integrationtests.py

      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\integrationtests.xml))

after_test:
  # Get a rough overview about what happened in the tests.
  # This is not part of the actual testing but pure convenience.
  - python clcache.py -s
